"""
Core Schemas and State Definitions for Claims Triage.

Defines Pydantic models for structured outputs and TypedDict state schema
for the LangGraph state graph.
"""

from typing import List, Dict, Any, Optional, Literal
from typing_extensions import TypedDict
from pydantic import BaseModel, Field


class TriageDecision(BaseModel):
    """
    Structured triage output generated by the LLM reasoning node
    and validated by Pydantic.
    """
    recommendation: Literal["FAST_TRACK", "MANUAL_REVIEW", "SIU_FRAUD_INVESTIGATION", "REQUEST_INFO"] = Field(
        ...,
        description="The primary triage routing decision."
    )
    confidence_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence in the triage recommendation."
    )
    fraud_risk_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Assessed fraud probability based on claims history and loss indicators."
    )
    is_covered: bool = Field(
        default=True,
        description="True if the loss type is covered under the policy declarations."
    )
    policy_exclusions_identified: List[str] = Field(
        default_factory=list,
        description="List of policy exclusion clause IDs triggered (e.g. SEC-EXCL-301)."
    )
    missing_documents: List[str] = Field(
        default_factory=list,
        description="List of mandatory documents missing from submission (e.g. 'police_report', 'repair_estimate')."
    )
    citations: List[str] = Field(
        default_factory=list,
        description="Specific policy clause citations and document excerpts grounding the decision."
    )
    reasoning: str = Field(
        ...,
        description="Step-by-step audit rationale justifying the recommendation."
    )
    estimated_settlement_amount: Optional[float] = Field(
        default=None,
        description="Total estimated payable amount after applying deductible."
    )
    applicable_deductible: Optional[float] = Field(
        default=None,
        description="Deductible applied according to policy terms."
    )


class TriageState(TypedDict, total=False):
    """
    Shared state container passed between nodes in the LangGraph workflow.
    """
    claim_id: str
    policy_number: str
    incident_date: str
    claimant_statement: str
    raw_documents: List[Dict[str, Any]]
    sanitized_documents: List[Dict[str, Any]]
    pii_entities_scrubbed: List[str]
    policy_details: Dict[str, Any]
    claims_history: Dict[str, Any]
    parsed_documents: Dict[str, Any]
    retrieved_policy_clauses: List[Dict[str, Any]]
    decision: Optional[TriageDecision]
    requires_human_review: bool
    escalation_reason: Optional[str]
    route: str
    errors: List[str]
